name: CI
on:
  push:
    branches: [ "main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest #If running on windows change this line to runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Give permission to gradlew
        run: chmod +x gradlew
      - name: Run test
        run: ./gradlew clean build
      - name: Run test coverage 
        run: ./gradlew jacocoTestReport 
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/app/build/customJacocoDir/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
                       
     
