name: CI
on:
  push:
    branches: [ "main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: windows-latest #If running on windows change this line to runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Give permission to gradlew
        run: chmod +x gradlew
      - name: Run test
        run: ./gradlew clean build
      - name: Run test coverage 
        run: ./gradlew jacocoTestReport 
      - name : generate jacoco badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: build/customJacocoDir/test/jacocoTestReport.csv
             
     
